algoritmo "Calcular a quantidade de chuva"
// Função : Fazer o calculo da chuva e transferir a unidade
// Autor :  Caio
// Data : 15/08/2014
// Seção de Declarações 
var
   chuvaemp: real // entrada
   chuvaemm: real // saida
inicio
// Seção de Comandos 
   escreva ("Informe a quantidade de chuva em polegadas ")
   leia (chuvaemp)
   chuvaemm := chuvaemp * 25.4
   escreval ("A quantidade de chuva equivalente em milimetros é de", chuvaemm)
fimalgoritmo
