algoritmo "Salário"
// Função : Calcular a quantidade contida sobre o salário total do empregado
// Autor : Caio
// Data : 18/08/2014
// Seção de Declarações 
var
   salarioentrada: real // entrada
   totaldesalario: real // saida
inicio
// Seção de Comandos 
   escreva ("Informe o salário total que você recebe ao todo R$ ")
   leia (salarioentrada)
   totaldesalario := salarioentrada / 724.00
   escreval ("Você recebe ",totaldesalario:1:2, " salário(s) minimos")
   

fimalgoritmo
